### PR TITLE
Format all files to current ns-3 .clang-format rules

### PR DESCRIPTION
**Pull request by nondetalle**
Apply [ns-3 .clang-format rules](https://gitlab.com/nsnam/ns-3-dev/-/blob/6c87965ae208d7f6fa6ecd37e8d567ca16df159d/.clang-format) to all files of the module using ns-3's [check-style-clang-format.py](https://gitlab.com/nsnam/ns-3-dev/-/blob/edf72af4bffddc8f3b03ee1e8d931dc526fe7470/utils/check-style-clang-format.py). 
No additional changes beyond formatting.

This merge is meant to break up a previous [huge pull request](https://github.com/signetlabdei/lorawan/pull/135) into more digestible pieces.

### CODE REVIEW

**Comment by nondetalle** [comment]
@pagmatt If it's ok for you, now I'll focus on restoring github workflows on the line of [the ones of ns-3](https://gitlab.com/nsnam/ns-3-dev/-/tree/edf72af4bffddc8f3b03ee1e8d931dc526fe7470/utils/tests).

**Comment by pagmatt** [comment]
Makes sense to me! How do you plan to do that? Fork on Gitlab the ns-3 repo and set this as a submodule, or define the CI here? I believe we may run out of CI time if we do it here for all the ns-3 mainline CI actions

**Comment by nondetalle** [comment]
The problem I see with the submodule option is that CI actions would not run automatically for MRs. It would require an additional fetch & commit from the ns-3 fork perspective to activate the CI actions there, right? And this would only work on changes already merged, so contributors would not be able to fix the problems directly in the MR.

I propose we first try to fix the CI here. I was thinking of cutting down the number of actions in the main ns-3 repo. For instance, we can start by running them exclusively on ubuntu images with a single compiler (as they are now) and focus on building, testing, formatting and documentation.

**Comment by pagmatt** [comment]
The MR one is a good point.
Let's try to fix the CI here then, ideally I'd like to keep publishing the documentation on Github pages as well. I can take care of that myself actually.

**Pull request merged**
